services:
  # Infrastructure
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: userdb,authdb,postdb,admindb,targetdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - microservices_network

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI
    networks:
      - microservices_network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - microservices_network

  # Core services
  service-registry:
    build: ./service-registry
    container_name: service-registry
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices_network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices_network

  # Microservices
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_EXPORTER_ZIPKIN_PROTOCOL=http/json
      - OTEL_SERVICE_NAME=auth-service
    networks:
      - microservices_network

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - postgres
      - rabbitmq
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices_network

  post-service:
    build: ./post-service
    container_name: post-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - mongodb
      - rabbitmq
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices_network

  admin-service:
    build: ./admin-service
    container_name: admin-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - postgres
      - rabbitmq
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices_network

  target-service:
    build: ./target-service
    container_name: target-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
      - postgres
      - rabbitmq
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices_network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
      - rabbitmq
      - zipkin
    environment:
      - ZIPKIN_URL=http://zipkin:9411
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices_network

volumes:
  postgres_data:
  mongodb_data:

networks:
  microservices_network:
    driver: bridge