version: '3.8'

services:
  # Infrastructure
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: userdb,authdb,postdb,admindb,targetdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI

  # Core services
  service-registry:
    build: ./service-registry
    container_name: service-registry
    restart: always
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - service-registry

  # Microservices
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - service-registry
      - postgres
      - rabbitmq

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - postgres
      - rabbitmq

  post-service:
    build: ./post-service
    container_name: post-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - mongodb
      - rabbitmq

  admin-service:
    build: ./admin-service
    container_name: admin-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - postgres
      - rabbitmq

  target-service:
    build: ./target-service
    container_name: target-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
      - postgres
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
      - rabbitmq

volumes:
  postgres_data:
  mongodb_data:
